# Generated by Django 3.0.2 on 2021-03-31 19:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default=None, max_length=40)),
                ('contact_number', models.CharField(default=None, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(default=None, max_length=100)),
                ('threshold_value', models.IntegerField(default=None)),
                ('threshold_value_unit', models.CharField(default=None, max_length=10)),
                ('current_quantity', models.IntegerField(default=None)),
                ('supply_status', models.CharField(choices=[('Low', 'Low Supply'), ('Mid', 'In-Supply (Med)'), ('High', 'In-Supply (High)')], default='Low', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(default=None, max_length=25)),
                ('business_name', models.CharField(default=None, max_length=50)),
                ('contact_person', models.CharField(default=None, max_length=40, unique=True)),
                ('address1', models.CharField(default=None, max_length=40)),
                ('address2', models.CharField(default=None, max_length=40)),
                ('special_notes', models.TextField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Delivered_Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_restock', models.IntegerField(default=None)),
                ('delivery_date', models.DateField(default=datetime.datetime(2021, 3, 31, 19, 8, 6, 603949, tzinfo=utc))),
                ('parcel_number', models.CharField(default=None, max_length=50)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dentalapp.Material')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dentalapp.Supplier')),
            ],
        ),
    ]
