# Generated by Django 3.0.2 on 2021-04-01 06:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('Perishable', 'Perishable'), ('Non-Perishable', 'Non-Perishable')], default='Non-Perishable', max_length=25),
        ),
        migrations.AlterField(
            model_name='delivered_material',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 1, 6, 49, 3, 862394, tzinfo=utc)),
        ),
    ]
