# Generated by Django 3.0.14 on 2021-04-16 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0013_required_material_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='procedure_material_name',
        ),
        migrations.AddField(
            model_name='required_material',
            name='quantity_unit',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='required_material',
            name='procedure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedure_required_material', to='dentalapp.Procedure'),
        ),
    ]
