# Generated by Django 3.0.14 on 2021-04-20 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0018_delivered_material_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivered_material',
            name='expiry_date',
        ),
    ]
