# Generated by Django 3.0.3 on 2021-04-15 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0011_auto_20210415_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='procedure_material_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dentalapp.Material'),
        ),
    ]
