# Generated by Django 3.0.14 on 2021-04-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0016_auto_20210419_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('Non-Perishable', 'Non-Perishable'), ('Perishable', 'Perishable')], default='Non-Perishable', max_length=25),
        ),
    ]
