# Generated by Django 3.0.14 on 2021-05-19 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0024_auto_20210519_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='threshold_value',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
