# Generated by Django 3.0.2 on 2021-02-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0004_remove_supplier_supplier_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
        migrations.AddField(
            model_name='supplier',
            name='address1',
            field=models.CharField(default=None, max_length=40, verbose_name='Address Line 1'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address2',
            field=models.CharField(default=None, max_length=40, verbose_name='Address Line 2'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='business_name',
            field=models.CharField(default=None, max_length=50, verbose_name='Business Name'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_number',
            field=models.IntegerField(default=None, verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='special_notes',
            field=models.CharField(default=None, max_length=100, verbose_name='Special Notes'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(default=None, max_length=40, verbose_name='Contact Person'),
        ),
    ]
