# Generated by Django 3.0.2 on 2021-02-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0005_auto_20210228_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address1',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address2',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='business_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_number',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='special_notes',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
