# Generated by Django 3.0.3 on 2021-04-10 12:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0009_auto_20210410_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default=None, max_length=40)),
                ('contact_number', models.CharField(default=None, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(default=None, max_length=100)),
                ('material_type', models.CharField(choices=[('Perishable', 'Perishable'), ('Non-Perishable', 'Non-Perishable')], default='Non-Perishable', max_length=25)),
                ('threshold_value_unit', models.CharField(default=None, max_length=10)),
                ('threshold_value', models.IntegerField(default=None)),
                ('current_quantity', models.IntegerField(default=None)),
                ('supply_status', models.CharField(choices=[('Low', 'Low Supply'), ('Mid', 'In-Supply (Med)'), ('High', 'In-Supply (High)')], default='Low', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(default=None, max_length=40, unique=True),
        ),
        migrations.CreateModel(
            name='Delivered_Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_restock', models.IntegerField(default=None)),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('parcel_number', models.CharField(default=None, max_length=50)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dentalapp.Material')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dentalapp.Supplier')),
            ],
        ),
    ]
