# Generated by Django 3.0.14 on 2021-04-18 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0014_auto_20210416_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
