# Generated by Django 3.0.14 on 2021-04-19 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0017_auto_20210419_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivered_material',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
