# Generated by Django 3.0.14 on 2021-05-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0027_auto_20210520_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('Non-Perishable', 'Non-Perishable'), ('Perishable', 'Perishable')], default='Non-Perishable', max_length=25),
        ),
    ]
