# Generated by Django 3.0.14 on 2021-05-20 07:45

import dentalapp.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0028_auto_20210520_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivered_material',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[dentalapp.models.Delivered_Material.validate_date]),
        ),
    ]
