# Generated by Django 3.0.2 on 2021-02-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_id',
            field=models.IntegerField(max_length=10, verbose_name='Supplier ID'),
        ),
    ]
