# Generated by Django 3.0.2 on 2021-02-27 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0003_auto_20210223_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='supplier_id',
        ),
    ]
