# Generated by Django 3.0.2 on 2021-02-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0006_auto_20210228_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact_number',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
