# Generated by Django 3.0.3 on 2021-04-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0008_auto_20210410_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
