# Generated by Django 3.0.3 on 2021-04-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0012_auto_20210415_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='required_material',
            name='quantity',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
