# Generated by Django 3.0.14 on 2021-04-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0015_material_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='required_material',
            name='quantity_unit',
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('Perishable', 'Perishable'), ('Non-Perishable', 'Non-Perishable')], default='Non-Perishable', max_length=25),
        ),
    ]
