# Generated by Django 3.0.14 on 2021-04-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0021_checkout_excessmaterials'),
    ]

    operations = [
        migrations.AddField(
            model_name='required_material',
            name='quantity_unit',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='required_material',
            name='quantity',
            field=models.IntegerField(default=None),
        ),
    ]
