# Generated by Django 3.0.14 on 2021-06-01 05:26

import dentalapp.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0029_auto_20210520_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_number',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='material',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now, error_messages={'required': 'Invalid Date Input'}, validators=[dentalapp.models.Material.validate_date]),
        ),
        migrations.AlterField(
            model_name='material',
            name='threshold_value',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_number',
            field=models.IntegerField(default=None),
        ),
    ]
