# Generated by Django 3.0.14 on 2021-06-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0030_auto_20210601_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_number',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_number',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
