# Generated by Django 3.0.3 on 2021-04-15 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0010_auto_20210410_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(default=None, max_length=50)),
                ('price', models.IntegerField(default=None)),
                ('procedure_material_name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('Perishable', 'Perishable'), ('Non-Perishable', 'Non-Perishable')], max_length=25),
        ),
        migrations.AlterField(
            model_name='material',
            name='supply_status',
            field=models.CharField(choices=[('Low', 'Low Supply'), ('Mid', 'In-Supply (Med)'), ('High', 'In-Supply (High)')], max_length=20),
        ),
        migrations.CreateModel(
            name='Required_Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dentalapp.Material')),
                ('procedure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dentalapp.Procedure')),
            ],
        ),
    ]
