# Generated by Django 3.0.2 on 2021-04-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0010_auto_20210410_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('Perishable', 'Perishable'), ('Non-Perishable', 'Non-Perishable')], max_length=25),
        ),
        migrations.AlterField(
            model_name='material',
            name='supply_status',
            field=models.CharField(choices=[('Low', 'Low Supply'), ('Mid', 'In-Supply (Med)'), ('High', 'In-Supply (High)')], max_length=20),
        ),
    ]
