# Generated by Django 3.0.2 on 2021-04-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0011_auto_20210413_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='current_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='supply_status',
            field=models.CharField(choices=[('Low', 'Low Supply'), ('Mid', 'In-Supply (Med)'), ('High', 'In-Supply (High)')], default='Low', max_length=20),
        ),
    ]
