# Generated by Django 3.0.2 on 2021-04-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0012_auto_20210413_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='supply_status',
            field=models.CharField(choices=[('Low Supply', 'Low Supply'), ('In-Supply (Med)', 'In-Supply (Med)'), ('In-Supply (High)', 'In-Supply (High)')], default='Low Supply', max_length=20),
        ),
    ]
