# Generated by Django 3.0.2 on 2021-04-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0013_auto_20210413_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='supply_status',
            field=models.CharField(default='Low', max_length=20),
        ),
    ]
