# Generated by Django 3.0.2 on 2021-04-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0020_reservation_reservationprocedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Finished', 'Finished')], default='Scheduled', max_length=20),
        ),
    ]
