# Generated by Django 3.0.2 on 2021-04-22 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0021_reservation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default=None, max_length=50)),
                ('reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dentalapp.Reservation')),
            ],
        ),
        migrations.AlterField(
            model_name='required_material',
            name='quantity',
            field=models.IntegerField(default=None, max_length=50),
        ),
        migrations.CreateModel(
            name='ExcessMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excess_quantity', models.IntegerField(default=None)),
                ('checkout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dentalapp.Checkout')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dentalapp.Material')),
            ],
        ),
    ]
