# Generated by Django 3.0.14 on 2021-04-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0022_auto_20210427_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Finished', 'Finished')], default='Scheduled', max_length=20),
        ),
    ]
