# Generated by Django 3.0.2 on 2021-04-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0022_auto_20210422_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='required_material',
            name='quantity',
            field=models.IntegerField(default=None),
        ),
    ]
