# Generated by Django 3.0.2 on 2021-04-28 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0023_reservation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='required_material',
            name='quantity_unit',
        ),
    ]
