# Generated by Django 3.0.14 on 2021-05-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0023_reservation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='required_material',
            name='quantity_unit',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='invoice_number',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_name',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Finished', 'Finished'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20),
        ),
    ]
