# Generated by Django 3.0.2 on 2021-04-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0024_remove_required_material_quantity_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Finished', 'Finished'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20),
        ),
    ]
