# Generated by Django 3.0.2 on 2021-04-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0025_auto_20210429_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='invoice_number',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
